### ISSUE TITLE
Require update 

### ISSUE THREAD

**Issue by zakblacki** [hekl0/Werewolf#1]
Is this available on play store ? 

I updated the project androidx API 30 as well dependencies 
and changed translation vietnam to english 

but the facebook login need a better explanation for newcomer we cannot login in the app as tester

**Comment by hekl0** [comment]
Hi zak,

Thank you for your interest in the project. Unfortunately, it is not on play store as it still have some error (due to the fact that we didn't have backend server, I was just using a database to keep track of data). The reason for you to not be able to login is the facebook login API I used earlier is deprecated, thus we should update a newer facebook API version for the app.

**Comment by zakblacki** [comment]
Thank you for responding, 
I thought I need to submit first the app review request before I could use all the features 
Also what kind of Permissions features is the app requesting besides user_friends ?

As for he deprecated code if you could point me directly in the activity class required I will try to update.

**Comment by zakblacki** [comment]
Hi,

So this backend server is gonna be huge issue ....
I updated the deprecated code inside LoginActivity (I will push later) and I manage to connect but now I have another crash this line 
`VoiceCallService.rtcEngine = RtcEngine.create(getBaseContext(), "aed16bb36aa0410ba115391fb945692c", new EventHandler());` Inside  MainActivity is causing the bug  
for now it seem commenting the line temporary workaround 

Thanks !

**Comment by hekl0** [comment]
Back then, I was using [Agora.io](https://www.agora.io/en/) for text chat and voice chat, and I think the API is deprecated also :(. Honestly, I think that the project is really outdated (I developed it 3 years ago) and still have many bugs that I couldn't resolve at that time. My advice would be that you should develop your own version of Werewolf since I haven't programmed Android for 2 years so I might not be able to help you continue this project, I am really sorry!

**Comment by zakblacki** [comment]
Alright, If you remember the bugs that were present at the time I'd appreciate if you could mention them 
I will try to resolve them.
It's too bad this is a really good project it  would be a lose to abandon it there's a whole community currently looking for working stable app at the moment there isn't one on play store worth using. 
Not to mention you could make a good passive income with ads. 

Edit : Workaround for the bug mentioned up by including  older native support 

```
 ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a"
        }
```
Edit 2 : Changed  `loginButton.setReadPermissions(Arrays.asList("public_profile"));` to 
` loginButton.setPermissions(Arrays.asList("public_profile"));` in LoginActivity 

Now i have to switch to firebase database if you could just tell me what were you storing data with the current database

**Comment by hekl0** [comment]
Back then, I didn't know how to make a server so the project only had the front-end (the app) and the database (realtime database on firebase). Normally, the structure of a project should be front-end <-> back-end/server <-> database, but my project was only front-end <-> database. Therefore, I was having problems/bugs with updating users' status (online or offline) and deleting room if it is empty. This project depends on the front-end/app to send the signal to the database to change the status variable or delete the room if it is the last person in the room; however, if the users decide to force stop the app or kill it (go to home -> views all running apps -> kill the app) instead of pressing back button to exit, the app will be killed immediately and it will not be able to send the update data to the database.

My solution to the problem: Creating a back-end server to detect if users are online or not, by making the app to send "online data" to the server every minute and if it stopped sending -> the user is offline and thus, we should update the users' status and update the list of rooms.

For your second question, I was storing lists of users, list of rooms, in-game data for each room, chat for each room. This is a snapshot of the database: [data.txt](https://github.com/hekl0/Werewolf/files/5502043/data.txt.txt)

**Comment by zakblacki** [comment]
Thank you for the explanation I will try working on it 
If I have more question I will let you know
